developerportfolio/urls.py
from django.contrib import admin
from django.urls import path

from django.conf import settings

from django.conf.urls.static import static

import jobs.views
import main.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',main.views.home, name = 'main-home'),
    path('job/',jobs.views.home, name = 'job-home'),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models

class Blog(models.Model):
    blog_title = models.CharField(max_length = 100)
    blog_author = models.CharField(max_length = 100)
    blog_date = models.DateField()
    blog_description = models.TextField()
    blog_image = models.ImageField(upload_to='images/') # Blog images

jobs/models.py
from django.db import models

class Job(models.Model):
    image = models.ImageField(upload_to='images/') # Research thumbnail
    summary = models.CharField(max_length = 500)
    title = models.CharField(max_length = 100)

main/models.py
from django.db import models
from django import forms


class Education(models.Model):
    college_name = models.CharField(max_length = 200)
    start_date = models.DateField()
    end_date = models.DateField()
    degree = models.CharField(max_length = 100)
    stream = models.CharField(max_length = 100)

    def __str__(self):
        return self.college_name

class EducationResponsibilities(models.Model):
    description = models.CharField(max_length = 1000)
    education = models.ForeignKey(Education, on_delete=models.CASCADE,)
    def __str__(self):
        return self.description[:20] + ", " + self.education.college_name


class Experience(models.Model):
    company_name = models.CharField(max_length = 150)
    profile = models.CharField(max_length = 150)
    start_date = models.DateField()
    end_date = models.DateField()
    def __str__(self):
        return self.company_name


class ExperienceResponsibilities(models.Model):
    description = models.CharField(max_length = 1000)
    experience = models.ForeignKey(Experience, on_delete=models.CASCADE,)
    def __str__(self):
        return self.description[:20] + ", " + self.experience.company_name

class Publication(models.Model):
    paper_title = models.CharField(max_length = 150)
    paper_abstract = models.TextField()
    paper_published_date = models.DateField()
    def __str__(self):
        return self.paper_title

class AboutMe(models.Model):
    about_me = models.TextField()
    name = models.CharField(max_length = 100)
    my_summary = models.CharField(max_length=200) # Research Scholar | Food Scientist | Workaholic | Nutritionist | Social Activist
    resume = models.FileField(upload_to = 'resume/')
    def __str__(self):
        return self.name
        
class Skill(models.Model):
    name = models.CharField(max_length = 100)
    def __str__(self):
        return self.name

class Achievement(models.Model):
    description = models.CharField(max_length = 500)
    year = models.CharField(max_length=200, null = True)
    order_in = models.IntegerField(unique=True)
    def __str__(self):
        return f"Order: {self.order_in}" + " " +self.year + " " + self.description

class Certification(models.Model):
    title = models.CharField(max_length=150)
    certification_date = models.DateField()
    certificate_file = models.FileField(upload_to='certificates/')

    def __str__(self):
        return self.title

class ContactForm(forms.Form):
    name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Name'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'Email'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Message'}))

blog/views.py
from django.shortcuts import render

# Create your views here.

jobs/views.py
from django.shortcuts import render

def home(request):
    return render(request,'jobs/home.html')

main/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import ContactForm, AboutMe, Education, EducationResponsibilities , Experience , ExperienceResponsibilities, Publication , Skill, Achievement, Certification
from django.core.mail import EmailMultiAlternatives
from django.conf import settings


def home(request):
    if request.method == 'POST':
        contact_us = ContactForm(request.POST)
        if contact_us.is_valid():
            name = contact_us.cleaned_data.get('name')
            email = contact_us.cleaned_data.get('email')
            message = contact_us.cleaned_data.get('message')
            
            subject = f'Contact request from personal website by - {name}'
            text_content = f'Hi I am, {name}. {message} Sender Details: Name: {name} Email: {email}'
            html_content = f'<p>Hi I am, <strong>{name}</strong>,<br/><br/><br/> {message} <br/><br/><br/><br/>Sender Details: <br/>Name: {name}<br/>Email: {email}</p>'
            
            # Certifique-se de que EMAIL_RECEIVER está definido nas configurações
            msg = EmailMultiAlternatives(subject, text_content, settings.EMAIL_HOST_USER, [settings.EMAIL_RECEIVER])
            msg.attach_alternative(html_content, "text/html")
            msg.send()

            messages.success(request, 'Thanks for contacting us! We will get back to you soon.')
            
            return redirect('main-home')
    else:
        contact_us = ContactForm()

    about_me = AboutMe.objects.first()
    educations = Education.objects.all().order_by('-start_date')
    educationResponsibilities = EducationResponsibilities.objects.all()
    experienceResponsibilities = ExperienceResponsibilities.objects.all()
    experiences = Experience.objects.all().order_by('-start_date')
    publications = Publication.objects.all()
    skills = Skill.objects.all()
    achievements = Achievement.objects.all().order_by('-year')
    certifications = Certification.objects.all()

    data = {
        'about_me' : about_me,
        'educations' : educations,
        'educationResponsibilities':educationResponsibilities,
        'experienceResponsibilities' : experienceResponsibilities,
        'experiences' : experiences,
        'publications' : publications,
        'skills' : skills,
        'achievements' : achievements,
        'certifications': certifications,
        'contact_us':contact_us
    }
    
    return render(request, 'main/index.html', data)

jobs/templates/jobs/home.html
Hi

main/templates/main/index.html
<!DOCTYPE html>
{% load static %}
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{{ about_me.name}}</title>
    <link rel="shortcut icon" href={% static 'main/favicon.ico' %} type="image/x-icon" />
    <link rel="icon" href={% static 'main/favicon.ico' %} type="image/x-icon" />
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900" rel="stylesheet" />
    <link rel="stylesheet" href={% static 'main/libs/font-awesome/css/font-awesome.min.css' %} />
    <link href={% static 'main/css/styles.css' %} rel="stylesheet" />
    <link href={% static 'main/css/bootstrap.min.css' %} rel="stylesheet" />
</head>

<body translate="no">
    <div id="mobile-menu-open" class="shadow-large">
        <i class="fa fa-bars" aria-hidden="true"></i>
    </div>
    <!-- End #mobile-menu-toggle -->
    <header>
        <div id="mobile-menu-close">
            <span>Close</span> <i class="fa fa-times" aria-hidden="true"></i>
        </div>
        <ul id="menu" class="shadow">
            <li>
                <a href="#about">About</a>
            </li>
            <li>
                <a href="#publications">Publications</a>
            </li>
            <li>
                <a href="#education">Education</a>
            </li>
            <li>
                <a href="#experience">Experience</a>
            </li>
            <li>
                <a href="#skills">Skills</a>
            </li>
            <li>
                <a href="#achievements">Achievements</a>
            </li>
            <li>
                <a href="#contact">Contact</a>
            </li>
        </ul>
    </header>
    <!-- End header -->

    <div id="lead">
        <div id="lead-content">
            <h1>{{ about_me.name}}</h1>
            <h2>
                {{ about_me.my_summary }}
            </h2>
            <a href={{about_me.resume.path}} target="_blank" class="btn-rounded-white" download>Download Resume</a>
        </div>
        <!-- End #lead-content -->

        <div id="lead-overlay"></div>

        <div id="lead-down">
            <span>
                <i class="fa fa-chevron-down" aria-hidden="true"></i>
            </span>
        </div>
        <!-- End #lead-down -->
    </div>
    <!-- End #lead -->

    <div id="about">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <h2 class="heading">About Me</h2>
                </div>
                <div class="col-md-8">
                    <p>
                        {{about_me.about_me}}
                    </p>
                </div>
            </div>
        </div>
    </div>
    <!-- End #about -->

    <!-- Publication Starts -->
    <div id="publications" class="background-alt">
        <h2 class="heading">Publications</h2>

        <div class="container">
            <div class="row">
                {% for publication in publications %}
                <div class="publications shadow-large">
                    <div class="publications-image">
                        <img alt={% static 'main/images/research.jpg' %} src={% static 'main/images/research.jpg' %} />
                    </div>
                    <!-- End .publications-image -->
                    <div class="publications-info">
                        <h3>{{ publication.paper_title }}</h3>
                        <p>
                            {{ publication.paper_abstract }}
                        </p>
                        <a href="#">View Publication</a>
                    </div>

                    <!-- End .publications-info -->
                </div>
                {% endfor %}
                <!-- End .publications -->
            </div>
        </div>

    </div>
    <!-- End #publications -->
    <!-- Education Starts -->
    <div id="education">
        <h2 class="heading">Education</h2>
        {% for education in educations %}
        <div class="education-block">


            <h3>{{education.college_name}}</h3>
            <span class="education-date">{{education.start_date |date:"F Y"}} -
                {{education.end_date |date:"F Y"}}</span>
            <h4>{{education.degree}} {{education.stream}}</h4>
            <ul>
                {% for responsibility in education.educationresponsibilities_set.all %}

                <li>
                    {{responsibility.description}}
                </li>
                {% endfor %}
            </ul>

        </div>
        {% endfor %}
        <!-- End .education-block -->
    </div>
    <!-- End #education -->

    <!-- Experience Starts -->

    <div id="experience" class="background-alt">
        <h2 class="heading">Experience</h2>
        <div id="experience-timeline">
            {% for experience in experiences %}
            <div data-date="September 2015 – September 2016">
                <h3>{{experience.company_name}}</h3>
                <h4>{{experience.profile}}</h4>
                {% for responsibility in experience.experienceresponsibilities_set.all %}
                <p>
                    {{responsibility.description}}
                </p>
                {% endfor %}
            </div>
            {% endfor %}
        </div>
    </div>
    <!-- End #experience -->

    <div id="skills">
        <h2 class="heading">Skills</h2>
        <ul>
            {% for skill in skills %}
            <li>{{skill}}</li>
            {% endfor %}
        </ul>
    </div>
    <!-- End #skills -->

    <!-- Achievement Starts -->
    <div id="achievements" class="background-alt">
        <h2 class="heading">Achievements</h2>
        <div class="atimeline">
            <ol>
                {% for achievement in achievements %}
                <li>
                    <div>
                        <time>{{achievement.time}}</time>
                        {{achievement.description}}
                    </div>
                </li>
                {% endfor %}

                <li></li>
            </ol>
        </div>
        <div class="arrows">
            <button class="arrow arrow__prev disabled" disabled>
                <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/162656/arrow_prev.svg" alt="prev atimeline arrow"
                    class="black-button">
            </button>
            <button class="arrow arrow__next">
                <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/162656/arrow_next.svg" alt="next atimeline arrow"
                    class="black-button">
            </button>
        </div>
        <!-- </section> -->
    </div>
    <!-- Certifications Starts -->
    <div id="certifications">
        <h2 class="heading">Certifications</h2>
        <div class="container">
            <div class="row">
                {% for certification in certifications %}
                <div class="certification-block">
                    <h3>{{ certification.title }}</h3>
                    <span class="certification-date">{{ certification.certification_date |date:"F Y" }}</span>
                    <a href="{{ certification.certificate_file.url }}" target="_blank">View Certification</a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
<!-- End #certifications -->

    <!-- Achievement Ends -->

    <div id="contact">
        {% if messages %}
        {% for message in messages %}
        <div style="color: white; size: 1.2rem;">
            {{message}}
        </div>
        {% endfor %}
        {% endif %}
        <h2>Get in Touch</h2>
        <div id="contact-form">
            <p>Kaue Andreatti Curti</p>
            <p>Email -> kauecurti@hotmail.com</p>
           
            
        </div>
        <!-- End #contact-form -->
    </div>
    <!-- End #contact -->

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-sm-5 copyright">
                    <p>
                        Copyright &copy; 2025 {{about_me.name}}
                    </p>
                </div>
                <div class="col-sm-2 top">
                    <span id="to-top">
                        <i class="fa fa-chevron-up" aria-hidden="true"></i>
                    </span>
                </div>
                <div class="col-sm-5 social">
                    <ul>
                        <li>
                            <a href="https://github.com/" target="_blank"><i class="fa fa-github"
                                    aria-hidden="true"></i></a>
                        </li>
                        <li>
                            <a href="https://stackoverflow.com/" target="_blank"><i class="fa fa-stack-overflow"
                                    aria-hidden="true"></i></a>
                        </li>
                        <li>
                            <a href="https://linkedin.com/" target="_blank"><i class="fa fa-linkedin"
                                    aria-hidden="true"></i></a>
                        </li>
                        <li>
                            <a href="https://www.facebook.com/" target="_blank"><i class="fa fa-facebook"
                                    aria-hidden="true"></i></a>
                        </li>
                        <li>
                            <a href="https://twitter.com/" target="_blank"><i class="fa fa-twitter"
                                    aria-hidden="true"></i></a>
                        </li>
                        <li>
                            <a href="https://plus.google.com/" target="_blank"><i class="fa fa-google-plus"
                                    aria-hidden="true"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    <!-- End footer -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/hammer.js/2.0.8/hammer.min.js'></script>
    <script src={% static 'main/js/achievement.js' %}></script>
    <script src={% static 'main/js/scripts.js' %}></script>
</body>

</html>